// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNeafEhxGnlSufLwnx1acnMY6fuoJVj_M',
    appId: '1:808424847353:web:e72416ba8bcdd2f2c8af28',
    messagingSenderId: '808424847353',
    projectId: 'terracode-8e26c',
    authDomain: 'terracode-8e26c.firebaseapp.com',
    storageBucket: 'terracode-8e26c.firebasestorage.app',
    measurementId: 'G-L3EQ2WMFD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUynDtpTL-Kfun2qsrctLtkUQtANwiHwg',
    appId: '1:808424847353:android:3c7a6af21d387beac8af28',
    messagingSenderId: '808424847353',
    projectId: 'terracode-8e26c',
    storageBucket: 'terracode-8e26c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6KHNnUL9Qpp7gL2W0EAV4gUnyCC8J6ik',
    appId: '1:808424847353:ios:5dc2a7956d61243fc8af28',
    messagingSenderId: '808424847353',
    projectId: 'terracode-8e26c',
    storageBucket: 'terracode-8e26c.firebasestorage.app',
    iosBundleId: 'com.example.terracodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6KHNnUL9Qpp7gL2W0EAV4gUnyCC8J6ik',
    appId: '1:808424847353:ios:5dc2a7956d61243fc8af28',
    messagingSenderId: '808424847353',
    projectId: 'terracode-8e26c',
    storageBucket: 'terracode-8e26c.firebasestorage.app',
    iosBundleId: 'com.example.terracodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNeafEhxGnlSufLwnx1acnMY6fuoJVj_M',
    appId: '1:808424847353:web:fc57306521f24a90c8af28',
    messagingSenderId: '808424847353',
    projectId: 'terracode-8e26c',
    authDomain: 'terracode-8e26c.firebaseapp.com',
    storageBucket: 'terracode-8e26c.firebasestorage.app',
    measurementId: 'G-RJZNP2R07S',
  );
}
